export const CONFIG = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  LOGOS: [
    'adobe',
    'airbnb',
    'apple',
    'baidu',
    'bmw',
    'canva',
    'facebook',
    'ferrari',
    'google',
    'hsbc',
    'linkedin',
    'microsoft',
    'pinterest',
    'reddit',
    'samsung',
    'shopify',
    'slack',
    'spotify',
    'tencent',
    'tesla',
    'twitch',
    'twitter',
    'youtube',
    'zoom',
    'lg',
    'nintendo',
  ],
};
